---
csl: apa.csl
bibliography: ref.bib
link-citations: yes
output:
  bookdown::html_document2:
    number_sections: false
    self_contained: true
    pandoc_args: "--mathjax"
    mathjax: NULL
    theme: NULL
    template: /home/liao/R/x86_64-pc-linux-gnu-library/3.4/rmarkdown/rmd/fragment/default.html
---
<!--For external images, set self_contained: false-->

<!--yaml
---
mermaid: false
mathjax: false
mathjax_autoNumber: false
highlight: true
title: "閱讀筆記：Origins of Human Communication"
description: ""
tags: [Linguistics, Psychology, Evolution, 中文]
---
yaml-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	fig.dim = c(7, 4),
	message = FALSE,
	warning = FALSE,
	comment = "",
	#fig.path = "../../assets/",
	out.width = "100%"
)
library(knitr)
```


去年秋天在準備研究所甄試時，發現市面上的語言學概論課本對於筆試幾乎沒有任何幫助，於是去找認知語言學相關的專著和文章來閱讀。我找的第一本書是 [George Lakoff](https://en.wikipedia.org/wiki/George_Lakoff) 的 [*Metaphors We Live By*](https://en.wikipedia.org/wiki/Metaphors_We_Live_By)。<!--more-->閱讀此書時，發覺自己又面臨一個陌生、龐大、擁有一堆術語的領域，而且認知語言學中的「認知」似乎和我所熟悉的「認知」心理學不太一樣，很難從自己熟悉的角度去切入作者的想法。於是我換了一本書 -- @geeraerts2006。這本書由一篇篇獨立的文章組成，每篇文章由一或兩位從事認知語言學相關研究的學者撰寫。在 @geeraerts2006 中，我發現一個熟悉的名字 -- [Michael Tomasello](https://en.wikipedia.org/wiki/Michael_Tomasello)。當時我對 Tomasello 並不熟悉，僅知道他是個有名的心理學家，研究興趣與這些關鍵字有關：*Language acquisition*, *Joint attention*, *Primate cognition*。閱讀 Tomasello 的文章後，我終於開始抓到一點認知語言學的想法。果然，要了解一個陌生的領域最好還是從自己熟悉的思維下手。


## 語言到底是什麼？

這個出現在語概課本第一章的問題，通常會說明人類語言和動物的溝通有什麼**本質上**的不同，並且指出人類語言具有結構、可組合的特性等等。但這些說明只是描述人類語言的特性，但對於語言是什麼，或更精確地說 -- 語言如何產生 (包含認知處理上、生理發展上、演化歷史上)，並未提供有洞見的解釋。

我想認知語言學的主要貢獻在於，其看見**語言以外**的世界，強調認知系統對於形塑語言的影響。對於語言的分析，因此需跨出「語言」，擴展到人類的認知系統。這真的是充滿雄心壯志的抱負，但我並不覺得這帶來的影響是全然正面的，因為面對人類心智運作的問題時，事情會變得**非常非常非常複雜**。特別是語言，從人類語言的相關研究可以發現語言真的很「雜亂 (noisy)」 (相較於視覺系統)。這使將戰線拉得如此廣泛的認知語言學可能變得十分混亂，在沒有透徹理解一個現象中比較基礎的因素前，就直接研究更複雜的整體現象[^basis]。這也是為何我對於 ***語言是什麼*** 這個問題感到困惑。我一直找不到一個清晰、穩固的基礎，作為評斷各種對語言的看法與理論的基準。我們似乎根本不了解語言是什麼，卻常在很抽象的層次上試圖說明語言是什麼。

於是，我決定先從 Tomasello 的專著下手，因為他的研究興趣是語言 (甚至是人類) 的演化，而就我所學過的東西而言，演化論應是僅次於數學，最可靠的一種想法。


[^basis]: 我覺得這是人類心智科學普遍的情況，因為人類大腦非常複雜、難以窺視其運作，不像物理、化學等基礎學科，我們難以知曉心智的哪些功能與現象是基礎的，哪些是複雜的。


## 看見更基礎的元素

看完 *Origins of Human Communication* [@tomasello2008] 後，不得不佩服 Tomasello 這位學者。剛了解他研究對象是嬰兒與靈長類動物、研究主題是心理學和語言學時，不太能理解為什麼，只以為他是興趣廣泛。讀完書後才了解到，這些內容都與 Tomasello 想回答的問題密切相關 -- 語言的起源。

Tomasello 厲害的地方在於其能夠跳脫「語言」的框架，嘗試找出語言要能運作所需的**更基礎的元素**。而要找出這些基礎的元素，需要跳脫過去語言相關研究關注的主體 -- 成年人類的語言使用，將目光聚焦在「尚未」發展出語言的族群上 -- 黑猩猩與人類嬰兒，藉此找出哪些因素造成成年人類和這兩個族群有如此不同的語言表現。

例如，「*口語*」在語言學中可說是最受關注的焦點 (相較於「文字」與「手勢」)，所以許多對於語言的研究與分析都是以口語作為基礎。但 Tomasello 強調了「手勢」的重要性。要了解「語言 (language)」，我們應該先了解「溝通 (communication)」，因為語言只是人類溝通的一種形式，而「*指向 (pointing)*」與「*比手畫腳 (pantomiming)*」則是人類溝通的另外兩種重要方式。「手勢」( *指向* 與 *比手畫腳* ) 的重要性在於，由於其所能攜帶的資訊量遠少於語言，其特別容易突顯人類溝通時，溝通者需具備的社會認知結構。這裡以書中提到的例子說明：

> 我和妳正在去圖書館的路上。走到圖書館外面時，我指向停放腳踏車的地方。這時妳應該會感到奇怪，因為妳不知道我要表達什麼。
> 
> 但假設如果妳剛和男朋友分手，而且妳和我都知道這件事，而我指向的地方停有妳男友的腳踏車，那這個手勢就和上一種情況有完全不同的意義 (代表：「妳男友可能在圖書館裡，妳確定要進去嗎？」)。
> 
> 又或者，假設我指向的地方停著妳之前被偷的腳踏車，那這個手勢又代表著完全不一樣的意義。

在上述的幾個例子中，同樣的手勢，甚至在同樣的客觀背景 (physical context) 下，表達了相異且十分複雜的意義。這些例子的差異僅來自於**我和妳先前的共同經驗**。這種現象在人類溝通中 (包含手勢與語言) 隨處可見。因此，這裡需要回答的問題是，**什麼樣的認知結構使得人類在溝通時，能夠自然而然地形成上述的詮釋**。


## 黑猩猩 vs. 人類 {#chimp}

關於上述的問題，一個最精簡的答案是溝通者理解彼此是「有意圖 (intentional)」的個體，所以在我指向腳踏車停放處時，妳會進行類似的推論：「他為什麼指向那裡，他**想**告訴我什麼？」但這只是個過於簡化的答案，因為黑猩猩也能理解溝通的對象是有意圖的，但黑猩猩卻無法發展出人類般複雜的溝通方式。例如，在餵食黑猩猩的情境中，若黑猩猩觀察到實驗者**不願意** (unwilling) 餵食時，黑猩猩會表現出失望的行為；但如果實驗者是因為其它原因 (例如，餵食孔太小或是因為其它事情分心) **無法** (unable) 餵食，黑猩猩會持續耐心的等待 [@call2004]。

所以，人類溝通運作的關鍵不僅僅是能夠理解彼此具有意圖，還需要其它關鍵因素。Tomasello 在經過大量對於黑猩猩與人類嬰兒手勢溝通 (gestural communication) 的研究後，指出人類與黑猩猩之間存在一項重要的差異 -- 人類的溝通本質上是合作性的 (cooperative)，但黑猩猩的溝通幾乎是自我中心與命令式的 (imperative)。換言之，黑猩猩的溝通意圖僅有**要求 (request)** 其他黑猩猩或人去做自己要他們達成的事情；人類的溝通意圖則不只侷限於要求，更多情況下是為了**提供對方資訊 (inform)** (例如前述的圖書館例子：我透過手勢告知妳**對妳 (但不是我) 而言**有用的資訊)，或是單純為了**分享 (sharing)** (例如：「今天發生了 ... ，心情好糟喔！」)。值得注意的是，即使人類意圖要求別人為自己做事情的時候，仍然是以「合作性」的方式提出要求。例如我們通常使用婉轉的方式提出要求 (例如，使用問句)，在對方完成我們的要求後，表達感謝甚至是必須的。


## 溝通的合作性結構

人類溝通中的「合作性」結構與人類的社會認知結構 (social-cognitive infrastructure) 之間關係密不可分。要有合作性的對話產生，溝通者之間必須建立一種抽象、共享的**共同經驗 (common ground)** -- 溝通者彼此都知道，且也都知道「對方知道我知道」的事情。承接上述圖書館的例子：

> 妳知道我指向停腳踏車處是為了告訴妳：「妳男友在圖書館裡」。這是因為我知道妳和妳男友分手，而妳也知道我知道這件事。

值得注意的是這裡包含所謂**遞迴 (recursive) 的認知結構**：妳必須知道「我知道妳和妳男友分手」這件事，上述溝通的情況才會產生。換言之，如果妳並未告訴過我妳和妳男友分手這件事，但我從其它管道得知了這件事，妳對我指向圖書館外的腳踏車就不會有「他在告訴我，我男友在圖書館內」這個詮釋 (縱使妳看到了妳男友的腳踏車)[^recursive]。因此，形成共同經驗的前提是，溝通者必須具備一種「遞迴讀心 (recursive mindreading)」的認知能力。

當合作性的溝通是建立在共同經驗上，溝通者才能從共同經驗中推斷哪些資訊是對方感興趣的。同時，因為預設溝通者的動機是合作的，日常溝通中，我們才會以這種方式詮釋模糊的訊息：

> 某個陌生人拍拍妳的肩膀再指向妳右邊臉頰，妳應該會認為他在告訴妳：「妳臉頰上有東西」。

這個手勢明明有千百種詮釋方式，但因為人類會隱性地預設對方是善意的、提供的是對自己有用的訊息，所以會形成這種詮釋。

[^recursive]: 或是另一種更複雜的情況：妳並未告訴過我妳和妳男友分手這件事，但我從其它管道得知了這件事，而妳又從某個管道得知「我從其它管道得知妳和妳男友分手」這件事。換言之，我知道妳和妳男友分手，妳也知道我知道這件事 (這種結構還能持續無限遞迴下去)，但因為我們從未將此事納入我們的共同經驗 (common ground) 中，亦即這件事並未在我們過去的互動中「公開」(妳並未告訴我)，這件事就不會造成妳認為我是在告訴妳「妳男友在圖書館」。



## 語言的起源

人類的溝通，不論是*指向 (pointing)*、*比手畫腳 (pantomiming)* 或*口語* (spoken language) 皆是建立在上述合作性的溝通結構[^argue]。基本上，「合作」可說是造成今日語言的面貌的最重要的原因之一。


[^argue]: 值得注意的是，當溝通中的合作性結構消失時，可能代表著非常可怕的事情即將發生。試想自己見過最火爆的爭吵，對話者說話 (「吼」話或許比較貼切) 不是為了提供訊息或分享，而是單純希望壓制對方、讓對方閉嘴。若透過聲音彰顯的怒氣不足以抑制對方，甚至可能使用肢體暴力。


### 句法

人類語言中複雜的句法不會無緣無故出現，一定存在某種使用上的功能性壓力 (functional pressure)，才使語言演化出句法。人類溝通中的合作性結構提供了這種壓力。黑猩猩溝通的意圖僅有*要求 (requesting)* ，而要表達要求僅需非常精簡的 (或甚至不需要) 句法：試想祈使句的文法有多精簡 (例如，「(你) 走開」)。這是因為 *要求* 的溝通意圖所涉及的情境非常簡單 -- 當下 (時間點)、你 (主體)、去做某事 (事件)。但人類的溝通是合作性的，我們溝通的意圖多半是為了*提供訊息 (informing) *和*分享 (sharing)*。

*提供訊息* 涉及的情境就比單純要求別人作某事要複雜的多了，因為提供訊息給對方常需涉及**不在當下 (時間上或空間上) 的事件** (對方不知道的事情，例如，「我在回來的路上看到眼鏡蛇」，常常不是在溝通當下能看到的事情)。*提供訊息* 這種溝通上的需求因而就使句法變得必要 -- 我們需要標示訊息中**不在對方當下注意力可及範圍內的人或事件**、需要標示**_誰_ 對 _誰_ 做了什麼 _事_**，而句法可以達成這些目的。分享所見所聞又比起提供訊息涉及更為複雜的情境，因為我們需要完整地描述所見所聞或甚至「說故事」。這使得溝通必須仰賴更加複雜句法才能達成目的，所以語言中開始出現更複雜結構，例如，子句結構，以描述許多彼此環環相扣的事件。


### 先有手勢，才有口語

語言的相關研究十分強調 *口語* 的重要性，甚至有關尼安德塔人是否具備語言能力的爭論都被簡化成尼安德塔人會不會說話的爭論[^neanderthal] [@arensburg1989; @danastasio2013]。口語固然有其重要性，但 Tomasello 認為口語不是語言的起源。口語是在手語之後 (或伴隨手語）出現的，而手語則是由比手畫腳演變而成。主要論點如下：

1. 黑猩猩，目前在演化樹上與人類最接近的親屬，能透過手勢彈性地傳達多種訊息。但黑猩猩的發聲器官卻相當侷限，其發出的聲音僅能用於固定的情緒表達。因此在演化歷史上，「手勢」會是個比較好的材料，較可能作為形塑語言的基礎。

1. *口語* (spoken language) 是約定俗成 (conventionalized) 與專斷的 (arbitrary)。換句話說，同樣的物體，例如「月亮」，在不同語言會有完全不同的形式 (發音)。因此，**除非經過約定**，口語本身並無法「攜帶」意義。相反地，手勢本身就能蘊含意義：

    - *指向 (pointing)* 能透過引導對方的注意力至你我之外的第三個物體，期望對方在看到物體後能做出適當的推論[^pointing]，解讀我欲傳達的訊息。但「未約定俗成的口語」就只是無意義的聲音而已，而聲音無法像「*指向*」一般具有彈性操弄對方注意力焦點的功能 (可以指向這裡、那裡、我、你、他)，因為聲音只能將對方注意力吸引到自己身上。
    
    - *比手畫腳 (pantomiming)* 比起*指向 (pointing)* 又更能彈性地傳達意義。*比手畫腳* 是透過手勢去模擬真實世界中發生的事情，因此即使溝通者之間的共同經驗 (common ground) 很少，也能透過這種方式溝通 (試想自己是如何在語言不通的外國生存的)。
    
    因此，演化歷史上比較可能的情況是先有手勢，而手勢中能傳達較豐富意義之 *比手畫腳* 逐漸被約定俗成，進而形成了手語[^infant]。手勢中的 *指向* 則保留自今，變成口語的輔助。而口語則是在手語出現之後才演化出來，並取代原本手語的角色。

1. 在適當的環境之下，人類能自然而然發展出手語。手語在各方面都與我們所熟知的「語言」沒有什麼太大的區別 -- 使用手語時，大腦語言區或活化；手語和所有語言一樣富含規則，違反句文法的使用也會讓手語使用者覺得「怪怪的」。事實上，`語言 = 口語` 的概念似乎太過深植人心，導致許多人在知道「原來使用手語時，大腦語言區會『亮起』」時，感到非常訝異 (包含我)。但如果在演化歷史上，語言本來就是從視覺模態 (visual modality) 轉變成聽覺模態 (auditory modality)，那今日所觀察到的手語現象就有相當自然的解釋。


[^neanderthal]: 當然，若尼安德塔人確實會說話，那確實 (至少從 @tomasello2008 的理論) 能證實其擁有語言能力。但這裡想強調的是，縱使尼安德塔人不會說話，**並不代表尼安德塔人不具有語言能力**。

[^pointing]: *指向 (pointing)* 所能傳達之訊息的複雜程度，受到溝通者之間的共同經驗 (common ground) 影響。摯友、家人之間有很許多共同經驗，所以一個 *指向* 就能傳達含有非常複雜意義的訊息。相反的，陌生人，或甚至是來自不同國家的陌生人，彼此的共同經驗就很少，因此無法透過 *指向* 傳達太過複雜的訊息。


[^infant]: 有趣的是，*口語* (spoken language) 與 *比手畫腳 (pantomiming)* 之間的對應關係也可在發展語言中的嬰兒身上見到。嬰兒在 1 歲到 2 歲的過程中，使用 *指向 (pointing)* 的頻率逐漸攀升，但使用 *比手畫腳 (pantomiming)* 與固定手勢 (conventional gestures) 的頻率卻持續下降。換句話說，*口語* 的功能在嬰兒語言發展過程中，逐漸取代了 *比手畫腳* 與固定手勢 [@tomasello2008, p.145 - 153]。


## 小結


> Truth is much too complicated to allow anything but approximations.
>
> --- John von Neumann

@tomasello2008 提供了一篇龐雜，但相當具有說服力的關於語言演化的故事。然而任何理論都是假的，包含 Tomasello 令人印象深刻的故事，有些理論卻是有用的。在這裡，演化論扮演相當好的角色 -- 它幫助我們思考、提出合理的猜測，去解釋人類那些看似彼此沒有任何關係的功能如何互相依存與支持，在演化歷史上孕育出新的功能。縱使這個故事是假的，它提供了許多能被驗證的假設。看著假設提出與驗證的過程，我似乎能在複雜到令人絕望的心智科學中，看見一條能夠前進的道路。


## 參考資料 {#references}

